### ISSUE TITLE
TypeError While Fetching YTMusic Equivalent Songs

### ISSUE THREAD

**Issue by DelusionalChicken** [Kan1shak/spotify-to-ytm#1]
Multiple playlists that contained this song stopped and displayed the exception below when it reached this song and refused to continue

Exception in thread Thread-8 (fetch_equivalents):
Traceback (most recent call last):
  File "C:\Users\{username}\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "C:\Users\{username}\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\{username}\spotify-to-ytm\gui.py", line 146, in fetch_equivalents
    title, artist, _, vid_id = yt.search_one(f"{song_title} {artist_name}")
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\{username}\spotify-to-ytm\src\yt_music.py", line 29, in search_one
    choice, confidence = process.extractOne(q, search_arr)
    ^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object

Song That it stops on:
You’re So Ugly When You Cry (feat. Bert of The Used) by The Funeral Portrait,The Used,robbietheused
https://open.spotify.com/track/3x4mzoX77tshwD7bKNxw5n?si=43b155739c274917

**Comment by DelusionalChicken** [comment]
another song that gives the same error:
Let Me Hear - Parasyte -the maxim- OP by Jonathan Parecki
https://open.spotify.com/track/5aJcdNob6KVL0K5phKR3EU?si=924b01aabc1c4ae9

**Comment by Kan1shak** [comment]
Thank you for reporting this! I've just pushed an update that should fix it.

Could you please:
1. Pull the latest changes
2. Test if the issue is resolved on your end

If you're still experiencing the problem, please let me know and provide any error messages you encounter.
